[project]
name = "cricfy-kodi-plugin"
version = "1.2.0"
description = "Cricfy Plugin for Kodi"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kodistubs>=21.0.0",
    "pycryptodomex>=3.23.0",
    "requests>=2.32.5",
]
