name: Build Cricfy Kodi Plugin

on:
  push:
    branches: [main]
    paths:
      - "plugin.video.cricfy/**"
      - ".python-version"
      - "pyproject.toml"
      - "uv.lock"
      - "main.py"
      - ".github/workflows/build.yml"
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras

      - name: Run main.py
        env:
          CRICFY_SECRET1: ${{ secrets.CRICFY_SECRET1 }}
          CRICFY_SECRET2: ${{ secrets.CRICFY_SECRET2 }}
          CRICFY_FIREBASE_API_KEY: ${{ secrets.CRICFY_FIREBASE_API_KEY }}
          CRICFY_FIREBASE_APP_ID: ${{ secrets.CRICFY_FIREBASE_APP_ID }}
          CRICFY_PACKAGE_NAME: ${{ secrets.CRICFY_PACKAGE_NAME }}
        run: uv run main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v5
        with:
          name: plugin.video.cricfy
          path: plugin.video.cricfy* # Wildcard is needed to include the enclosing folder

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v6
        with:
          name: plugin.video.cricfy
          path: dist

      - name: Zip the folder
        run: |
          cd dist
          zip -r plugin.video.cricfy-${{ github.ref_name }}.zip plugin.video.cricfy
          rm -rf plugin.video.cricfy

      - name: Create GitHub release and upload asset(s)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/**
          make_latest: true
          prerelease: false
          draft: false
          generate_release_notes: true


  pre-release:
    needs: build
    if:  ${{ ! startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v6
        with:
          name: plugin.video.cricfy
          path: dist

      - name: Zip the folder
        run: |
          cd dist
          zip -r plugin.video.cricfy-${{ github.ref_name }}.zip plugin.video.cricfy
          rm -rf plugin.video.cricfy

      - name: Generate tag
        id: gen_tag
        run: |
          echo "tag=${{ github.ref_name }}.$(date +'%Y.%m.%d.%H.%M')" >> $GITHUB_OUTPUT

      - name: Create GitHub release and upload asset(s)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.gen_tag.outputs.tag }}
          files: dist/**
          prerelease: true
          draft: false
          generate_release_notes: true
